WriterPlatformWeb/Controllers/Account/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WriterPlatformWeb.Models.Auth;
using WriterPlatformWeb.Services.Contracts.Interfaces;

namespace WriterPlatformWeb.Controllers.Account;

[Route("account")]
public class UserController : Controller
{
    private readonly IUserService _userService;

    public UserController(IUserService userService)
    {
        _userService = userService;
    }

    [HttpGet("login")]
    [AllowAnonymous]
    public IActionResult Login(string returnUrl = null)
    {
        ViewData["Title"] = "Авторизация";
        ViewData["ReturnUrl"] = returnUrl; // Временно не используется

        return View("Login");
    }

    [HttpPost("login")]
    [AllowAnonymous]
    public async Task<IActionResult> Login([FromForm] LoginModel model, string returnUrl = null)
    {
        if (ModelState.IsValid)
        {
            if (await _userService.AuthenticateUserAsync(model))
            {
                return string.IsNullOrEmpty(returnUrl) ? RedirectToAction("Index", "Home") : Redirect(returnUrl);
            }

            TempData["ErrorMessage"] = "Пользователь не существует";
        }

        return View(model);
    }

    [HttpGet("register")]
    [AllowAnonymous]
    public IActionResult Register(string returnUrl = null)
    {
        ViewData["Title"] = "Регистрация";
        ViewData["ReturnUrl"] = returnUrl; // Временно не используется

        return View("Register");
    }

    [HttpPost("register")]
    [AllowAnonymous]
    public async Task<IActionResult> Register([FromForm] RegisterModel model)
    {
        if (ModelState.IsValid)
        {
            if (await _userService.RegisterUserAsync(model))
            {
                return RedirectToAction("Index", "Home");
            }
            TempData["ErrorMessage"] = "Некорректные логин и(или) пароль";
        }

        return View(model);
    }

    [HttpPost("logout")]
    public async Task<IActionResult> Logout()
    {
        await _userService.LogoutAsync();
        return RedirectToAction("Index", "Home");
    }

    [HttpPost("delete")]
    [Authorize]
    public async Task<IActionResult> DeleteAccount()
    {
        var result = await _userService.DeleteUserAsync();
        if (result)
        {
            TempData["SuccessMessage"] = "Аккаунт успешно удален";
            return RedirectToAction("Index", "Home");
        }
        TempData["ErrorMessage"] = "Что-то пошло не так";
        return View("Settings");
    }
}

WriterPlatformWeb/Controllers/Admin/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WriterPlatformWeb.Models.ViewModel.Admin;
using WriterPlatformWeb.Services.Contracts.Interfaces;

namespace WriterPlatformWeb.Controllers.Admin;

[Route("admin")]
[Authorize(Roles = "Администратор,Administrator,Admin")]
public class AdminController : Controller
{
    private readonly IUserService _userService;
    private readonly IRoleService _roleService;
    private readonly IAuthorService _authorService;

    public AdminController(IUserService userService, IRoleService roleService, IAuthorService authorService)
    {
        _userService = userService;
        _roleService = roleService;
        _authorService = authorService;
    }

    [HttpGet("dashboard")]
    public async Task<IActionResult> Dashboard()
    {
        var users = await _userService.GetAllUsersAsync();
        var roles = await _roleService.GetAllRolesAsync();
        var authors = await _authorService.GetAllAuthorsAsync();


        var viewModel = new AdminViewModel
        {
            Users = users,
            Roles = roles,
            Authors = authors
        };

        return View("Admindashboard", viewModel);
    }
}

WriterPlatformWeb/Controllers/Work/WorkController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WriterPlatformWeb.Models.ViewModel.Work;
using WriterPlatformWeb.Services.Contracts.Interfaces;

namespace WriterPlatformWeb.Controllers.Work;

[Route("works")]
public class WorkController : Controller
{
    private readonly IWorkService _workService;
    private readonly IGenreService _genreService;
    private readonly IAuthorService _authorService;
    private readonly ICommentService _commentService;
    private const int WordsPerPage = 200;

    public WorkController(IWorkService workService, IGenreService genreService, IAuthorService authorService, ICommentService commentService)
    {
        _workService = workService;
        _genreService = genreService;
        _authorService = authorService;
        _commentService = commentService;
    }

    [HttpGet("{id:int}")]
    public async Task<IActionResult> GetWorkDetails([FromRoute] int id)
    {
        var work = await _workService.GetWorkByIdAsync(id);
        if (work == null)
        {
            return NotFound();
        }

        var comments = await _commentService.GetCommentsByWorkIdAsync(id);

        var viewModel = new WorkDetailsViewModel
        {
            Work = work,
            Comments = comments.ToArray()
        };

        return View("WorkDetails", viewModel);
    }

    [HttpGet("publish")]
    [Authorize]
    public async Task<IActionResult> PublishWorkForm()
    {
        var authors = await _authorService.GetAllAuthorsAsync();
        var genres = await _genreService.GetAllGenresAsync();

        var viewModel = new PublishWorkViewModel
        {
            Authors = authors,
            Genres = genres
        };

        return View("PublishWorkForm", viewModel);
    }

    [HttpPost("publish")]
    [Authorize]
    public async Task<IActionResult> PublishWork(PublishWorkViewModel model)
    {

        var work = await _workService.PublishWorkAsync(model.Work.Title, model.SelectedGenreId, model.SelectedAuthorId, model.Work.PublicationDate, model.Work.Text);

        if(work != null)
        {
            TempData["SuccessMessage"] = "Произведение успешно опубликовано.";
            return RedirectToAction("GetWorkDetails", new { workId = work.WorkId });
        }

        TempData["ErrorMessage"] = "Ошибка при публикации произведения";

        // Это если пройзодет ошибка загрузки
        model.Authors = await _authorService.GetAllAuthorsAsync();
        model.Genres = await _genreService.GetAllGenresAsync();

        return View("PublishWorkForm", model);
    }

    [HttpGet("read-text/{id}")]
    [Authorize]
    public async Task<IActionResult> ReadText([FromRoute] int id, int page = 1)
    {
        var fullText = await _workService.GetTextWork(id);

        if (string.IsNullOrEmpty(fullText))
        {
            return NotFound();
        }

        var words = fullText.Split(new[] { ' ' }, StringSplitOptions.RemoveEmptyEntries);


        var totalPages = (int)Math.Ceiling((double)words.Length / WordsPerPage);

        if (page < 1) page = 1;
        if (page > totalPages) page = totalPages;

        var pageWords = words.Skip((page - 1) * WordsPerPage).Take(WordsPerPage);

        var pageText = string.Join(" ", pageWords);

        var model = new PaginatedTextViewModel
        {
            WorkId = id,
            Text = pageText,
            CurrentPage = page,
            TotalPages = totalPages,
        };

        return View("Readtext", model);
    }
}

WriterPlatformWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewData["Title"]</title>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/style.css" rel="stylesheet" type="text/css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
    <body>
        <header>
            <nav class="navbar navbar-expand-lg header d-flex justify-content-between">
                <a asp-action="Index" asp-controller="Home">
                    <div class="navbar-brand">
                        <img src="/img/main_logo.png" alt="Logo">
                    </div>
                </a>
                <div class="separator"></div>
                <div class="collapse navbar-collapse">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Home" class="nav-link custom-fonts">Магазин</a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="PublishWorkForm" asp-controller="Work" class="nav-link custom-fonts">Опубликовать</a>
                        </li>
                    </ul>
                </div>
                <ul class="navbar-nav ml-auto">
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Администратор") || User.IsInRole("Administrator"))
                        {
                            <li class="nav-item" style="margin-right: 30px;">
                                <a asp-action="Dashboard" asp-controller="Admin" class="btn btn-outline-light">Админ панель</a>
                            </li>
                        }
                    }
                    else
                    {
                        <li class="nav-item" style="margin-right: 30px;">
                            <a asp-action="Login" asp-controller="User" class="btn btn-outline-light">Войти</a>
                        </li>
                    }
                    <li class="nav-item" style="margin-right:10px;">
                        <a asp-action="Settings" asp-controller="Settings">
                            <img src="/img/user_icon.png" alt="User Icon" style="width: 30px; height: 30px;">
                        </a>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <form asp-action="Logout" asp-controller="User" method="post" style="margin-left: 30px;">
                            <button type="submit" class="btn btn-outline-light">Выйти</button>
                        </form>
                    }
                </ul>
            </nav>
        </header>

        <div>
            @RenderBody()
        </div>
    </body>
</html>